version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build: .
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: mongodb://root:example@mongo:27017
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: "npm run server"

  poller:
    build: .
    restart: on-failure
    environment:
      DATABASE_URL: mongodb://root:example@mongo:27017
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: "npm run poller"
